### ISSUE TITLE
Seems to be an issue with current branch

### ISSUE THREAD

**Issue by montanaman2017** [oracle-quickstart/oci-cloudera#25]
I've tried the current branch and it does seem to install just fine, but there is no cloudera at all installed.  
After running
terraform init
terraform plan
terraform apply 
I get:
Apply complete! Resources: 69 added, 0 changed, 0 destroyed.

Outputs:

CLOUDERA MANAGER = http://xxx.xxx.xxx.xxx

but yet on the until server
a simple 
sudo yum list installed |grep -i cdh
shows nothing and grepping for
sudo ps aux |grep java   
also shows nothing running. 
Is this a known issue?
  All seems to again been deployed fine looking from what I'm seeing in the terraform.log

**Comment by smithzc** [comment]
The best place to check is /var/log/cloudera-OCI-deploy.log on the Utility node.  This will have install breadcrumbs. 

Also check /var/lib/cloud/instance/scripts/ on the same node, that's where the CloudInit deployment happens, and if cloudera-scm-server is not present on the host then try going there and running the script manually.   You should see the python deployment syntax in the first log file.

**Comment by smithzc** [comment]
Closing this (age out)
